
on: 
 push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: oss-devops
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_URL }}
        SLACK_CHANNEL: oss-devops
        SLACK_MESSAGE: "Post Content :rocket:"
        SLACK_TITLE: "Post Title"
        SLACK_USERNAME: rtCamp
